#
# FILE: `StockTrader/dbt/models/staging/tradier/schema.yml`
#

version: 2

models:
  - name: stg_tradier__dividends

    description: >
      Standardized historical dividend payments from Tradier API.
      For each symbol, contains dividends paid over past 18 months.
      Quarterly data refresh.

    columns:
      - name: symbol
        description: "Exchange-listed traded-as ticker symbol."
        tests:
          - not_null:
              config: {severity: error}
          - dbt_expectations.expect_column_values_to_match_regex:
              regex: "^[A-Z]{1,5}$"
              config: {severity: warn}

      - name: cash_amount
        description: "Dividend amount paid out in USD"
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0.0099
              max_value: 105.0
              config:
                severity: warn
                warn_if: ">25"
        meta:
          unit: "USD"
          precision: "hundredths"
          iqr_typical: "(0.27,0.94)"

      - name: ex_dividend_date
        description: "Ex-dividend date on which stock trades without dividend."
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: "'2024-01-01'"
              max_value: "current_date + interval '1 year'"
              config: {severity: warn}

      - name: frequency
        description: "Number of dividends paid per year."
        tests:
          - not_null:
              config: {severity: error}
          - accepted_values:
              values: [0, 1, 2, 4, 12]
              config: {severity: error}
              quote: false
        meta:
          frequency_mapping:
            0: "Special (ad-hoc)"
            1: "Annual"
            2: "Semi-Annual"
            4: "Quarterly"
            12: "Monthly"

      - name: dividend_type
        description: "Human-readable dividend type derived from frequency"
        tests:
          - not_null:
              config: {severity: error}
          - accepted_values:
              values: ['special', 'annual', 'semi_annual', 'quarterly', 'monthly', 'unknown']
              config: {severity: error}

      - name: is_regular_dividend
        description: >
          Boolean Flag to indicate regular dividneds.
          True=regular, False=special.
        tests:
          - not_null:
              config: {severity: error}
          - accepted_values:
              values: [true, false]
              config: {severity: error}

      - name: created_date
        description: "Date of ingest into system."
        tests:
          - not_null:
              config: {severity: error}
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: "'2025-01-01'"
              max_value: "current_date"
              config: {severity: warn}

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - symbol
            - ex_dividend_date
            - cash_amount
          config: {severity: warn}

      - dbt_expectations.expect_table_row_count_to_be_between:
          min_value: 1000
          max_value: 10000
          config: {severity: warn}
