#
# FILE: `StockTrader/dbt/models/staging/fred/schema.yml`
#

version: 2

models:
  - name: stg_fred__rates
    description: >
      Standardized interest rate data from FRED.
      Model contains monthly interest rate observations for use as risk-free rate proxy in option pricing models.
      Monthly data refresh.

    meta:
      owner: "deng"
      refresh_frequency: "monthly"
      data_source: "FRED_API"

    columns:
      - name: series_id
        description: FRED SERIES ID
        tests:
          - not_null:
              config:
                severity: error
          - accepted_values:
              values: ["TB3MS"]
              quote: true
              config:
                severity: error
                error_if: ">0"
        meta:
          valid_values: "TB3MS (3 Month T-BILLs)"

      - name: rate_date
        description: "First day of month on which interest rate becomes applicable."
        tests:
          - not_null:
              config:
                severity: warn
          - unique:
              config:
                severity: error
                error_if: ">5"
          # - dbt_utils.expression_is_true:
          #     expression: "extract(day from rate_date) = 1"
          #     config: {severity: error}
        meta:
          business_logic: "FRED rate publications set effective date to first of month"

      - name: rate_pct
        description: >
          Interest rate expressed as annual percentage (e.g. 4.72 = 4.72%).
          Used as risk-free rate proxy in options pricing models.
        tests:
          - not_null:
              config: {severity: error}