#
# FILE: `StockTrader/dbt/models/staging/fred/schema.yml`
#

version: 2

models:
  - name: stg_fred__rates
    description: >
      Standardized interest rate data from FRED.
      Model contains monthly interest rate observations for use as risk-free rate proxy in option pricing models.
      Monthly data refresh.

    meta:
      owner: "deng"
      refresh_frequency: "monthly"
      data_source: "FRED_API"

    columns:
      - name: series_id
        description: FRED SERIES ID
        tests:
          - not_null:
              config:
                severity: error
          - accepted_values:
              values: ["TB3MS"]
              quote: true
              config:
                severity: error
                error_if: ">0"
        meta:
          valid_values: "TB3MS (3 Month T-BILLs)"

      - name: rate_date
        description: "First day of month on which interest rate becomes applicable."
        tests:
          - not_null:
              config:
                severity: warn
          - unique:
              config:
                severity: error
                error_if: ">5"
          - dbt_expectations.expect_condition_to_be_true:
              condition: "day(rate_date) = 1"
              config: {severity: error}
          - dbt_expectations.expect_column_values_to_be_increasing:
              column_name: rate_date
              strictly: true
