#
# FILE: `StockTrader/dbt/models/staging/sources.yml`
#

version: 2

sources:
  - name: tradier_raw
    description: "Raw market data ingested from Tradier API (uvatradier) via Airflow"

    tables:
      - name: options_af
        description: "Daily options chain data for large-cap dividend stocks."
        meta:
          external_location: "/opt/stocktrader/data/warehouse/options_af/*.parquet"
      - name: quotes_af
        description: "Daily EOD stock quotes for large-cap dividend stocks."
        meta:
          external_location: "/opt/stocktrader/data/warehouse/quotes_af/*.parquet"
      - name: dividends_af
        description: "Historical dividend data ingested quarterly."
        meta:
          external_location: "/opt/stocktrader/data/warehouse/dividends_af/*.parquet"
          union_by_name: true
