#
# FILE: `StockTrader/dbt/models/staging/sources.yml`
#

version: 2

sources:
  - name: tradier_raw
    description: "Raw market data ingested from Tradier API (uvatradier) via Airflow"

    tables:
      - name: options_af
        description: "Daily options chain data for large-cap dividend stocks."
        meta:
          external_location: "../data/warehouse/options_af/*.parquet"
      - name: quotes_af
        description: "Daily EOD stock quotes for large-cap dividend stocks."
        meta:
          external_location: "../data/warehouse/quotes_af/*.parquet"
      - name: dividends_af
        description: "Historical dividend data ingested quarterly."
        meta:
          external_location: "../data/warehouse/dividends_af/*.parquet"
      - name: ohlcv_bars
        description: "Historical OHLCV daily bar data"
        meta:
          external_location: "../data/warehouse/ohlcv_bars/*.parquet"


  - name: fred_raw
    description: "Time series interest rate/macroeconomic data from Federal Reserve Data API"

    tables:
      - name: fred_af
        description: "Historical monthly interest rate data for use as risk-free proxies"
        meta:
          external_location: "../data/warehouse/fred_af/*.parquet"
