#
# FILE: `StockTrader/dbt/models/staging/sources.yml`
#

version: 2

sources:
  - name: tradier_raw
    description: "Raw market data ingested from Tradier API (uvatradier) via Airflow"

    tables:
      - name: options_af
        description: "Daily options chain data for large-cap dividend stocks."
        meta:
          external_location: "../data/warehouse/options_af/*.parquet"
      - name: quotes_af
        description: "Daily EOD stock quotes for large-cap dividend stocks."
        meta:
          external_location: "../data/warehouse/quotes_af/*.parquet"
      - name: dividends_af
        description: "Historical dividend data ingested quarterly."
        meta:
          external_location: "../data/warehouse/dividends_af/*.parquet"
      - name: ohlcv_bars
        description: "Historical OHLCV daily bar data"
        meta:
          external_location: "../data/warehouse/ohlcv_bars/*.parquet"

  - name: fred_raw
    description: "Time series interest rate/macroeconomic data from Federal Reserve Data API"

    loaded_at_field: created_date
    freshness:
      warn_after: {count:40, period:day}
      error_after: {count:60, period:day}

    tables:
      - name: fred_af
        description: "Historical monthly interest rate data for 3-Month Treasury Bill Securities (TB3MS). Used as risk-free proxy in option pricing model."
        meta:
          external_location: "../data/warehouse/fred_af/*.parquet"
          columns:
            - name: fred_date
              tests:
                - not_null
                - unique
            - name: fred_rate
              tests:
                - not_null
                - dbt_expectations.expect_column_values_to_be_between:
                    min_value: 0
                    max_value: 50
                    config:
                      severity: error
