#
# FILE: `StockTrader/.github/workflows/dbt-ci.yml`
#

#
# BASIC OUTLINE:
#   1. Repo Checkout + Establish Directories
#   2. Setup Python + Venv
#   3. Build dbt Docker Container
#   4. dbt Debug
#   5. Generate Sample Data For Tests
#   6. Run dbt Models on Sample Data
#   7. Run dbt Tests on Sample Data
#   8. Upload Artifact Reports
#


name: dbt CI

on:
  push:
    branches: [main]
    paths:
      - 'dbt/**'
      - '.github/workflows/dbt-ci.yml'
      - '.github/scripts/dbt-generate-test-data.py'
      - 'scripts/generate_dbt_universe_seed.sh'



jobs:
  dbt-test:
    runs-on: ubuntu-latest

    env:
      STOCK_TRADER_HOME: ${{ github.workspace }}
      STOCK_TRADER_MARKET_DATA: ${{ github.workspace }}/data
      STOCK_TRADER_DWH: ${{ github.workspace }}/data/warehouse
      STOCK_TRADER_LOG: ${{ github.workspace }}/logs

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Required Directories
        run: |
          mkdir -p artifacts/dbt-reports
          mkdir -p data/warehouse/{dividends_af,fred_af,options_af,quotes_af,ohlcv_bars}
          mkdir logs

          echo "Created Directories:"
          find {artifacts,data,logs} -type d

      - name: Validate Directory Structure
        run: |
          for d in artifacts/ data/ dbt/ logs/ scripts/ src/ utils/; do
            [ -d "$d" ] || { echo "ERROR: $d missing"; exit 1; }
          done

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Create + Start Python Virtual Environment
        run: |
          if command -v python3 &> /dev/null; then
            python3 -m venv venv
            source venv/bin/activate
            pip install -e .
          else
            python -m venv venv
            source venv/bin/activate
            pip install -e .
          fi

      - name: Build dbt Container
        run: docker compose build dbt

      - name: Install dbt Dependencies
        run: |
          docker compose run --rm dbt \
            dbt deps --profiles-dir /opt/stocktrader/dbt --target dev \
            2>&1 | tee artifacts/dbt-reports/dbt-deps.log

      - name: Check dbt Debug/Config
        run: |
          docker compose run --rm dbt \
            dbt debug --profiles-dir /opt/stocktrader/dbt --target dev \
            2>&1 | tee artifacts/dbt-reports/dbt-debug.log

      - name: Generate Test Data (quotes, options, dividends, ohlcv, fred)
        run: |
          source venv/bin/activate
          python .github/scripts/dbt-generate-test-data.py

      - name: Generate Symbol Universe CSV (largecap_all.csv)
        run: |
          bash scripts/generate_dbt_universe_seed.sh
          ls -l dbt/seeds/universe/largecap_all.csv
          head -n 12 dbt/seeds/universe/largecap_all.csv || true

      - name: Generate dbt Symbol Universe Seed
        run: |
          docker compose run --rm dbt \
            dbt seed --profiles-dir /opt/stocktrader/dbt --target dev --select largecap_all \
            2>&1 | tee artifacts/dbt-reports/dbt-seed.log

      - name: Run dbt Models
        run: |
          docker compose run --rm dbt \
            dbt run --profiles-dir /opt/stocktrader/dbt --target dev \
            2>&1 | tee artifacts/dbt-reports/dbt-run.log

      - name: Run dbt Tests
        run: |
          docker compose run --rm dbt \
            dbt test --profiles-dir /opt/stocktrader/dbt --target dev \
            2>&1 | tee artifacts/dbt-reports/dbt-test.log

      - name: Upload dbt Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dbt-results-${{ github.run_number }}
          path: |
            artifacts/
            dbt/target/
          retention-days: 5
